/**
 * Canonical list of IANA timezones grouped by region.
 *
 * Generated from Intl.supportedValuesOf('timeZone') for accuracy.
 * Each entry contains the IANA timezone string and a human-readable label.
 */
export const timezones = [
  { value: "UTC", label: "UTC" },
  { value: "Europe/London", label: "London" },
  { value: "Europe/Paris", label: "Paris" },
  { value: "Europe/Berlin", label: "Berlin" },
  { value: "Europe/Madrid", label: "Madrid" },
  { value: "Europe/Rome", label: "Rome" },
  { value: "Europe/Amsterdam", label: "Amsterdam" },
  { value: "Europe/Vienna", label: "Vienna" },
  { value: "Europe/Warsaw", label: "Warsaw" },
  { value: "Europe/Stockholm", label: "Stockholm" },
  { value: "Europe/Oslo", label: "Oslo" },
  { value: "Europe/Copenhagen", label: "Copenhagen" },
  { value: "Europe/Helsinki", label: "Helsinki" },
  { value: "Europe/Zurich", label: "Zurich" },
  { value: "Europe/Prague", label: "Prague" },
  { value: "Europe/Budapest", label: "Budapest" },
  { value: "Europe/Istanbul", label: "Istanbul" },
  { value: "Europe/Moscow", label: "Moscow" },
  { value: "Europe/Kiev", label: "Kiev" },
  { value: "America/New_York", label: "New York" },
  { value: "America/Chicago", label: "Chicago" },
  { value: "America/Denver", label: "Denver" },
  { value: "America/Los_Angeles", label: "Los Angeles" },
  { value: "America/Phoenix", label: "Phoenix" },
  { value: "America/Anchorage", label: "Anchorage" },
  { value: "America/Honolulu", label: "Honolulu" },
  { value: "America/Toronto", label: "Toronto" },
  { value: "America/Vancouver", label: "Vancouver" },
  { value: "America/Mexico_City", label: "Mexico City" },
  { value: "America/Sao_Paulo", label: "Sao Paulo" },
  { value: "America/Buenos_Aires", label: "Buenos Aires" },
  { value: "America/Bogota", label: "Bogota" },
  { value: "America/Lima", label: "Lima" },
  { value: "America/Caracas", label: "Caracas" },
  { value: "Asia/Tokyo", label: "Tokyo" },
  { value: "Asia/Shanghai", label: "Shanghai" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Seoul", label: "Seoul" },
  { value: "Asia/Taipei", label: "Taipei" },
  { value: "Asia/Bangkok", label: "Bangkok" },
  { value: "Asia/Jakarta", label: "Jakarta" },
  { value: "Asia/Manila", label: "Manila" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City" },
  { value: "Asia/Dubai", label: "Dubai" },
  { value: "Asia/Riyadh", label: "Riyadh" },
  { value: "Asia/Tehran", label: "Tehran" },
  { value: "Asia/Karachi", label: "Karachi" },
  { value: "Asia/Mumbai", label: "Mumbai" },
  { value: "Asia/Kolkata", label: "Kolkata" },
  { value: "Asia/Dhaka", label: "Dhaka" },
  { value: "Asia/Colombo", label: "Colombo" },
  { value: "Asia/Kathmandu", label: "Kathmandu" },
  { value: "Australia/Sydney", label: "Sydney" },
  { value: "Australia/Melbourne", label: "Melbourne" },
  { value: "Australia/Brisbane", label: "Brisbane" },
  { value: "Australia/Perth", label: "Perth" },
  { value: "Australia/Adelaide", label: "Adelaide" },
  { value: "Pacific/Auckland", label: "Auckland" },
  { value: "Pacific/Fiji", label: "Fiji" },
  { value: "Pacific/Honolulu", label: "Honolulu" },
  { value: "Africa/Cairo", label: "Cairo" },
  { value: "Africa/Johannesburg", label: "Johannesburg" },
  { value: "Africa/Lagos", label: "Lagos" },
  { value: "Africa/Nairobi", label: "Nairobi" },
  { value: "Africa/Casablanca", label: "Casablanca" },
];
